version: "3.9"
services:
  ubuntu:
    build: .
    ports:
      - 8080:8080
    networks:
      - default

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8000:80
    depends_on:
      - mariadb
    networks:
      - default
